# Infrastructure as Code
#
# The following tokens need to be set in the GitHub repository/organisation
# | Token            | Description                       |
# | ---------------- | --------------------------------- |
# | SNYK_TOKEN       | API key for https://snyk.io       |
# | BRIDGECREW_TOKEN | API key for https://bridgecrew.io |

name: IaC Workflow
on:
  push:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check configuration files for security issues
        uses: snyk/actions/iac@master
        # Snyk can be used to break the build when it detects security issues.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: iac/
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: snyk.sarif
  bridgecrew:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ secrets.BRIDGECREW_TOKEN }}
        download_external_modules: true
        soft_fail: true
        output_format: sarif
        directory: iac/
    - name: Expose report
      uses: actions/upload-artifact@main
      with:
        name: SARIF results
        path: bridgecrew.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: bridgecrew.sarif